version: '2.1'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  go:
    image: jancajthaml/go
    volumes:
      - .:/project
      - ./services/cnb-rates-import:/go/src/github.com/jancajthaml-openbank/cnb-rates-import
      - ./services/cnb-rates-rest:/go/src/github.com/jancajthaml-openbank/cnb-rates-rest
      - ./services/cnb-rates-batch:/go/src/github.com/jancajthaml-openbank/cnb-rates-batch
    working_dir: /project
    environment:
      - GOOS
      - GOARCH
      - GOPATH=/go
      - COMPOSE_PROJECT_NAME
    entrypoint: ["go"]
    privileged: true

  # -------------------------------------------------------------------------- #

  sync:
    extends: go
    entrypoint: ["/project/dev/lifecycle/sync"]

  # -------------------------------------------------------------------------- #

  update:
    extends: go
    entrypoint: ["/project/dev/lifecycle/update"]

  # -------------------------------------------------------------------------- #

  lint:
    extends: go
    entrypoint: ["/project/dev/lifecycle/lint"]

  # -------------------------------------------------------------------------- #

  sec:
    extends: go
    entrypoint: ["/project/dev/lifecycle/sec"]

  # -------------------------------------------------------------------------- #

  package:
    extends: go
    entrypoint: ["/project/dev/lifecycle/package"]

  # -------------------------------------------------------------------------- #

  release:
    extends: go
    entrypoint: ["/project/dev/lifecycle/release"]

  # -------------------------------------------------------------------------- #

  debian:
    extends: go
    entrypoint: ["/project/dev/lifecycle/debian"]

  # -------------------------------------------------------------------------- #

  test:
    extends: go
    entrypoint: ["/project/dev/lifecycle/test"]

  # -------------------------------------------------------------------------- #

  artifacts:
    build:
      dockerfile: Dockerfile
      context: .
    image: openbank/lake

# ---------------------------------------------------------------------------- #
