version: '2'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  go:
    build:
      dockerfile: dev/Dockerfile
      context: .
    image: openbankdev/cnb-rates-base
    volumes:
      - ./dev/lifecycle:/opt/lifecycle
      - .:/go/src/github.com/jancajthaml-openbank/cnb-rates
    working_dir: /go/src/github.com/jancajthaml-openbank/cnb-rates
    environment:
      - GOOS
      - GOARCH
      - GOPATH=/go
      - COMPOSE_PROJECT_NAME
    entrypoint: ["go"]

  # -------------------------------------------------------------------------- #

  service:
    build:
      dockerfile: Dockerfile
      context: .
    image: openbank/cnb-rates
    restart: "no"

  # -------------------------------------------------------------------------- #

  sync:
    extends: go
    entrypoint: ["dep"]
    command: ["ensure"]

  # -------------------------------------------------------------------------- #

  init:
    extends: go
    entrypoint: ["dep"]
    command: ["init"]

  # -------------------------------------------------------------------------- #

  update:
    extends: go
    entrypoint: ["dep"]
    command: ["ensure", "-update"]

  # -------------------------------------------------------------------------- #

  fetch:
    extends: go
    entrypoint: ["dep"]
    command: ["ensure", "-add", "github.com/logrusorgru/aurora"]

  # -------------------------------------------------------------------------- #

  lint:
    extends: go
    entrypoint: ["/opt/lifecycle/lint"]

  # -------------------------------------------------------------------------- #

  package:
    extends: go
    entrypoint: ["/opt/lifecycle/package"]
    command: ["-t", "linux"]

  # -------------------------------------------------------------------------- #

  release:
    extends: go
    entrypoint: ["/opt/lifecycle/release"]

  # -------------------------------------------------------------------------- #

  debian:
    extends: go
    entrypoint: ["/opt/lifecycle/debian"]

  # -------------------------------------------------------------------------- #

  test:
    extends: go
    environment:
      - GOMAXPROCS=1
    command: ["test", "-v", "./...", "-benchmem", "-bench=.", "-timeout=20s"]

  # -------------------------------------------------------------------------- #

  bbtest:
    build:
      context: .
      dockerfile: bbtest/Dockerfile
    image: openbankdev/cnb-rates_bbtest
    working_dir: /opt/bbtest
    environment:
      - COMPOSE_PROJECT_NAME
      - VERSION
    volumes:
      - ./reports/logs:/reports
      - ./bbtest:/opt/bbtest
      - journal:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

# ---------------------------------------------------------------------------- #

volumes:
  journal:
    driver: local

# ---------------------------------------------------------------------------- #
