#!/bin/sh

set -e

delete_service_files() {
  if [ -f "/lib/systemd/system/cnb-rates-rest.service" ] ; then
    rm /lib/systemd/system/cnb-rates-rest.service
  fi

  if [ -f "/lib/systemd/system/cnb-rates-import.service" ] ; then
    rm /lib/systemd/system/cnb-rates-import.service
  fi

  if [ -f "/lib/systemd/system/cnb-rates-batch.service" ] ; then
    rm /lib/systemd/system/cnb-rates-batch.service
  fi

  if [ -f "/lib/systemd/system/cnb-rates.service" ] ; then
    rm /lib/systemd/system/cnb-rates.service
  fi

  if [ -f "/lib/systemd/system/cnb-rates.path" ] ; then
    rm /lib/systemd/system/cnb-rates.path
  fi
}

delete_displace_files() {
  if [ -f "/etc/init/cnb-rates.conf" ] ; then
    rm /etc/init/cnb-rates.conf
  fi
}

unregister_cron_job() {
  crontab -l | grep -v 'cnb-rates-import' | crontab -
}

case "$1" in

  purge)
    # userdel openbank || :

    unregister_cron_job
    delete_service_files
    delete_displace_files

    (systemctl daemon-reload || :)
    (systemctl reset-failed || :)
  ;;

  remove)
    unregister_cron_job

    (systemctl -a -t service --no-legend  | awk '$1 ~ /cnb-rates/ { print $1 }' | xargs -I {} systemctl stop {} 2> /dev/null || :)
    (systemctl daemon-reload || :)

    delete_displace_files
  ;;

  upgrade|deconfigure)
    systemctl stop cnb-rates 2> /dev/null || :
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
