#!/bin/sh

set -e

delete() {
  if [ -f "${1}" ] ; then
    rm "${1}"
  fi
}

delete_service_files() {
  delete /etc/systemd/cnb-rates.service.wants/cnb-rates-rest.service
  delete /lib/systemd/system/cnb-rates-rest.service

  delete /etc/systemd/cnb-rates.service.wants/cnb-rates-import.timer
  delete /lib/systemd/system/cnb-rates-import.timer

  delete /lib/systemd/system/cnb-rates-import.service

  delete /etc/systemd/cnb-rates.service.wants/cnb-rates.path
  delete /lib/systemd/system/cnb-rates.path

  delete /etc/systemd/multi-user.target.wants/cnb-rates.service
  delete /lib/systemd/system/cnb-rates.service
}

delete_displace_files() {
  delete /etc/init/cnb-rates.conf
}

case "$1" in

  purge)
    delete_service_files
    delete_displace_files
    (systemctl daemon-reload >/dev/null 2>&1 || :)
    (systemctl reset-failed >/dev/null 2>&1 || :)
  ;;

  remove)
    (systemctl -a -t service --no-legend  | awk '$1 ~ /cnb-rates/ { print $1 }' | xargs -I {} systemctl stop {} 2> /dev/null || :)
    delete_displace_files
    (systemctl daemon-reload >/dev/null 2>&1 || :)
  ;;

  upgrade|deconfigure)
    (systemctl stop cnb-rates >/dev/null 2>&1 || :)
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
