#!/bin/bash

set -e

case "$1" in

    configure)
        if [ -f "/etc/init/cnb-rates.conf" ] ; then
            echo "Loading /etc/init/cnb-rates.conf"
            . /etc/init/cnb-rates.conf

            systemctl unmask cnb-rates.service >/dev/null
            systemctl enable cnb-rates.service >/dev/null
        else
            (>&2 echo "/etc/init/cnb-rates.conf file not found")
            exit 1
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        (>&2 echo "postinst called with unknown argument \ `$1`")
        exit 1
    ;;

esac

exit 0
