#!/bin/sh

set -e

if [ "$(ps -o comm -p 1 --no-headers | tr -d ' ')" = "systemd" ] ; then
  SYSTEMD_AVAIL=true
else
  SYSTEMD_AVAIL=false
fi

delete() {
  if [ -f "${1}" ] ; then
    rm "${1}"
  fi
}

delete_service_files() {
  delete /etc/systemd/cnb-rates.service.wants/cnb-rates-rest.service
  delete /lib/systemd/system/cnb-rates-rest.service

  delete /etc/systemd/cnb-rates.service.wants/cnb-rates-import.service
  delete /lib/systemd/system/cnb-rates-import.service

  delete /etc/systemd/cnb-rates.service.wants/cnb-rates.path
  delete /lib/systemd/system/cnb-rates.path

  delete /etc/systemd/multi-user.target.wants/cnb-rates.service
  delete /lib/systemd/system/cnb-rates.service
}

delete_displace_files() {
  delete /etc/init/cnb-rates.conf
}

unregister_cron_job() {
  crontab -l | grep -v 'cnb-rates-import' | crontab -
}

case "$1" in

  purge)
    unregister_cron_job

    delete_service_files
    delete_displace_files

    if [ ${SYSTEMD_AVAIL} ] ; then
      (systemctl daemon-reload || :)
      (systemctl reset-failed || :)
    fi
  ;;

  remove)
    unregister_cron_job

    if [ ${SYSTEMD_AVAIL} ] ; then
      (systemctl -a -t service --no-legend  | awk '$1 ~ /cnb-rates/ { print $1 }' | xargs -I {} systemctl stop {} 2> /dev/null || :)
    fi

    delete_displace_files

    if [ ${SYSTEMD_AVAIL} ] ; then
      (systemctl daemon-reload || :)
    fi
  ;;

  upgrade|deconfigure)
    if [ ${SYSTEMD_AVAIL} ] ; then
      systemctl stop cnb-rates 2> /dev/null || :
    fi
  ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
