#!/bin/sh

set -e

case "$1" in

  install|upgrade)

    if [ ! -f "/etc/init/cnb-rates.conf" ] ; then
      mkdir -p /etc/init
      touch /etc/init/cnb-rates.conf

      echo "CNB_RATES_STORAGE=/data" >> /etc/init/cnb-rates.conf
      echo "CNB_RATES_LOG_LEVEL=INFO" >> /etc/init/cnb-rates.conf
      echo "CNB_RATES_METRICS_REFRESHRATE=1s" >> /etc/init/cnb-rates.conf
      echo "CNB_RATES_CNB_GATEWAY=https://www.cnb.cz" >> /etc/init/cnb-rates.conf
      echo "CNB_RATES_METRICS_OUTPUT=/opt/cnb-rates/metrics/metrics.json" >> /etc/init/cnb-rates.conf
      echo "CNB_RATES_HTTP_PORT=4011" >> /etc/init/cnb-rates.conf
      echo "CNB_RATES_SECRETS=/opt/cnb-rates/secrets" >> /etc/init/cnb-rates.conf
    fi

    secrets=$(sed -n -e 's/^.*CNB_RATES_SECRETS=//p' /etc/init/cnb-rates.conf 2>/dev/null | awk '{gsub(/^ +| +$/,"")} {print $0}')

    if [ -z "${secrets}" ] ; then
      (>&2 echo "CNB_RATES_SECRETS are not defined at /etc/init/cnb-rates.conf")
      exit 1
    fi

    if [ ! -f "${secrets}/domain.local.crt" ] || [ ! -f "${secrets}/domain.local.key" ] ; then
      mkdir -p "${secrets}"

      openssl req \
        -x509 \
        -nodes \
        -newkey rsa:2048 \
        -keyout "${secrets}/domain.local.key" \
        -out "${secrets}/domain.local.crt" \
        -days 1 \
        -subj "/C=CZ/ST=Czechia/L=Prague/O=OpenBanking/OU=IT/CN=localhost/emailAddress=jan.cajthaml@gmail.com"
      echo "generated temporary certificates at ${secrets} valid for 24 hours"
    fi

  ;;

  abort-upgrade)
  ;;

  *)
    (>&2 echo "preinst called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
