version: 1

update_configs:
  - package_manager: "go:modules"
    directory: "/services/cnb-rates-rest"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/services/cnb-rates-import"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/services/cnb-rates-batch"
    update_schedule: "daily"
