#!/bin/sh

set -e

case "$1" in

  purge)
    systemctl stop cnb-rates.service
    systemctl disable cnb-rates.service
    crontab -l | grep -v '/openbank/services/cnb-rates/cnb-rates-unit' | crontab -
    (rm /lib/systemd/system/cnb-rates.service || :)
    (rm /lib/systemd/system/cnb-rates.service || :)
    (rm /etc/init/cnb-rates.conf || :)
    (rm /opt/cnb-rates/metrics/metrics.json || :)
    systemctl daemon-reload
    systemctl reset-failed
  ;;

  remove)
    systemctl mask cnb-rates.service
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    (>&2 echo "postrm called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
