#!/bin/sh

set -e

case "$1" in

  configure)
    if [ -f "/etc/init/cnb-rates.conf" ] ; then
      systemctl unmask cnb-rates.service >/dev/null
      systemctl enable cnb-rates.service >/dev/null
      schedule="30 14 * * * set -a; . /etc/init/cnb-rates.conf; set +a; systemd-cat -t \"cnb-rates-unit\" /openbank/services/cnb-rates/cnb-rates-unit"
      crontab -l | grep -v '/openbank/services/cnb-rates/cnb-rates-unit' | crontab -
      crontab -l | { cat; echo "${schedule}"; } | crontab -
      (systemctl start cnb-rates.service >/dev/null || :)
    else
      (>&2 echo "/etc/init/cnb-rates.conf file not found")
      exit 1
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    (>&2 echo "postinst called with unknown argument \ `$1`")
    exit 1
  ;;

esac

exit 0
