.nh
.TH "CNB-RATES-REST" "1" "Jul 2020" "CNB Rates REST" "OpenBank CNB Rates REST Server Manual"
.sp
.SH "NAME"
cnb-rates-rest \- starts openbank cnb exchange rates REST server
.SH "SYNOPSIS"
.sp
.nf
\fIcnb-rates-rest
.fi
.sp
.SH "DESCRIPTION"
.sp
The cnb rates rest provides REST server for accessing cnb rates
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
