.nh
.TH "CNB-RATES-IMPORT" "1" "Jul 2020" "CNB Rates Import" "OpenBank CNB Rates Cloud Import Manual"
.sp
.SH "NAME"
cnb-rates-import \- starts openbank cnb exchange rates cloud import
.SH "SYNOPSIS"
.sp
.nf
\fIcnb-rates-import
.fi
.sp
.SH "DESCRIPTION"
.sp
cnb rates import creates offline mirror of official cnb rates cloud
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
