.nh
.TH "CNB-RATES-BATCH" "1" "Jul 2020" "CNB Rates Batch" "OpenBank CNB Rates Batch Processing Manual"
.sp
.SH "NAME"
cnb-rates-batch \- starts openbank cnb exchange rates batch processing
.SH "SYNOPSIS"
.sp
.nf
\fIcnb-rates-batch
.fi
.sp
.SH "DESCRIPTION"
.sp
The cnb rates batch processes newly downloaded cnb rates
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
