name: Health Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '*/30 * * * *'

jobs:

  build:
    name: From Scratch Test
    runs-on: ubuntu-latest
    steps:

    - name: Prepare
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
      id: go

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install static dependencies (import)
      env:
        GO111MODULE: on
      working-directory: services/cnb-rates-import
      run: |
        go mod verify
        go mod tidy
        go mod vendor

    - name: Install static dependencies (batch)
      env:
        GO111MODULE: on
      working-directory: services/cnb-rates-batch
      run: |
        go mod verify
        go mod tidy
        go mod vendor

    - name: Install static dependencies (rest)
      env:
        GO111MODULE: on
      working-directory: services/cnb-rates-rest
      run: |
        go mod verify
        go mod tidy
        go mod vendor

    - name: Unit Test (import)
      working-directory: services/cnb-rates-import
      run:  |
        go test -v ./... -timeout=10s

    - name: Unit Test (batch)
      working-directory: services/cnb-rates-batch
      run:  |
        go test -v ./... -timeout=10s

    - name: Unit Test (rest)
      working-directory: services/cnb-rates-rest
      run:  |
        go test -v ./... -timeout=10s
