name: Health Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '*/30 * * * *'

jobs:

  build:
    name: From Scratch Test
    runs-on: ubuntu-latest
    steps:

    - name: Prepare
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install static dependencies (import)
      run: |
        cd services/cnb-rates-import
        GO111MODULE=on go mod verify
        GO111MODULE=on go mod tidy
        GO111MODULE=on go mod vendor

    - name: Install static dependencies (batch)
      run: |
        cd services/cnb-rates-batch
        GO111MODULE=on go mod verify
        GO111MODULE=on go mod tidy
        GO111MODULE=on go mod vendor

    - name: Install static dependencies (rest)
      run: |
        cd services/cnb-rates-rest
        GO111MODULE=on go mod verify
        GO111MODULE=on go mod tidy
        GO111MODULE=on go mod vendor

    - name: Unit Test (import)
      run:  |
        cd services/cnb-rates-import
        go test -v ./... -timeout=10s

    - name: Unit Test (batch)
      run:  |
        cd services/cnb-rates-batch
        go test -v ./... -timeout=10s

    - name: Unit Test (rest)
      run:  |
        cd services/cnb-rates-rest
        go test -v ./... -timeout=10s
